server:
  port: 8011
user:
  id: 100
  name: wjy
  birthday: 2011/11/11
  gender: true
  password: 123456
  parents: {father: Jack,Mother: Mary}
  roles: [admin,customer]
  address: {id: 300,address: aaaaa}

